replicaCount: 1
image:
  repository: 674182809289.dkr.ecr.us-east-1.amazonaws.com/ticketops-dev-bookings-worker
  tag: "6026ad8"
service:
  port: 80
  targetPort: 3000
envFromSecret: ticketops-db-secret
env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"
ingress:
  enabled: false
healthCheck:
  enabled: true
  path: /health
  port: 3000
