apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-prisma-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.backoffLimit }}
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: prisma-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: prisma-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          workingDir: /workspace/packages/prisma
          command: ["npm", "run", "migrate:deploy"]
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi