apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: admin-api-dev
  namespace: monitoring
  labels:
    release: monitoring-dev
spec:
  selector:
    matchLabels:
      app: admin-api-dev
  namespaceSelector:
    matchNames:
      - ticketops-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
