apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: "0.57.9"
      helm:
        valueFiles:
          - $values/monitoring/values/dev/fluent-bit-values.yaml
    - repoURL: https://github.com/sajidshaikh-01/ticketops-platform.git
      targetRevision: develop
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
