apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: "0.165.0"
      helm:
        valueFiles:
          - $values/monitoring/values/dev/otel-collector-values.yaml
    - repoURL: https://github.com/sajidshaikh-01/ticketops-platform.git
      targetRevision: develop
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
